basePath: /
definitions:
  models.Building:
    properties:
      city:
        type: string
      floors:
        type: integer
      id:
        type: integer
      name:
        type: string
      year_built:
        type: integer
    type: object
info:
  contact:
    email: zatrasz@ya.ru
    name: Михаил Токмачев
    url: https://t.me/Zatrasz
  description: |-
    ТЗ market_backend.
    Задание (Golang + PostgreSQL + Gin)
  title: Swagger API
  version: "1.0"
paths:
  /en/building:
    get:
      consumes:
      - application/json
      description: Принимает обязательные city, year_built, а так же не обязательные
        floors.
      parameters:
      - description: по названию города
        in: query
        name: city
        type: string
      - description: по году сдачи
        in: query
        name: year_built
        type: integer
      - description: кол-ву этажей
        in: query
        name: floors
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список домов
          schema:
            items:
              $ref: '#/definitions/models.Building'
            type: array
        "400":
          description: обязательные поля отсутствуют
          schema:
            type: string
        "500":
          description: Ошибка при получении данных
          schema:
            type: string
      summary: Возвращает список строений, с возможностью фильтрации по городу, году
        и кол-ву этажей(параметры не обязательные)
      tags:
      - Building
    post:
      consumes:
      - application/json
      description: Принимает обязательные поля name , city , year_built , а так же
        не обязательные floors.
      parameters:
      - description: Данные здания
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Building'
      produces:
      - application/json
      responses:
        "201":
          description: запись успешно добавлена
          schema:
            type: string
        "400":
          description: обязательные поля отсутствуют
          schema:
            type: string
        "409":
          description: название уже существует
          schema:
            type: string
        "500":
          description: Ошибка при добавлении данных
          schema:
            type: string
      summary: Создайте новой записи
      tags:
      - Building
swagger: "2.0"
